version: "3"

services:
  prometheus:
    image: bitnami/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"

  backend:
    image: backend:1
    ports:
      - 80:80
    environment:
      PG_NAME: data
      PG_USER: admin
      PG_PASSWORD: admin
      PG_HOST: db
    depends_on:
      db:
        condition: service_healthy


  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: data
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "admin" ]
    ports:
      - 5432:5432