version: "3"

services:
  prometheus:
    image: bitnami/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"

  backend:
    image: backend:1
    ports:
      - 80:80


  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'